# Generated by Django 4.1.4 on 2023-01-28 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listingobject_whatchlist_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 5, 30, 57, 347851, tzinfo=datetime.timezone.utc), verbose_name='date posted'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 5, 30, 57, 347851, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
        migrations.AddField(
            model_name='listingobject',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 5, 30, 57, 347851, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
