# Generated by Django 4.1.4 on 2023-01-31 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_pub_date_comment_pub_date_listingobject_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 26, 10, 525957, tzinfo=datetime.timezone.utc), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 26, 10, 525957, tzinfo=datetime.timezone.utc), verbose_name='date commented'),
        ),
        migrations.AlterField(
            model_name='listingobject',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 26, 10, 525957, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
